config/routes.rb
Rails.application.routes.draw do
  # resources :pages
  # root :to => 'pages#index'
  resources :pages do
    member do
        post :changer
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@posts = Todo.all
	    @post = Todo.new
	end

	def create
		@post = Todo.create(post_params)
		if @post.valid?
		else
		end
		redirect_to pages_path
	end

	def edit
		@post = Todo.find(params[:id])

	end

	def destroy
		@post = Todo.find(params[:id])
		@post.destroy
        redirect_to pages_path
	end

	def update
		@post = Todo.find(params[:id])
        updated = @post.update_attributes(task_name: params[:todolist][:task_name]) # returns true or flase
		if updated== true
        else
        end
        redirect_to pages_path

	end
	def changer
		@post = Todo.find(params[:id])
		if params[:flags] == "true"
			@post.update(complete: "complete")
		else
		end
		redirect_to pages_path
	
	end

	private
    def post_params
        params.require(:todo).permit(:task_name)
    end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mytodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<div style="background-color: lightyellow; height: 160px; border: 2px solid black">
<h1 style="text-align: center; padding-top: 50px; font-style: italic;">My todo list</h1>
</div>
<h2>Edit the task</h2>
<%= form_for @post, url: {action: 'update'} do |f| %>
  	<%= f.label :task_name, "Edit your task:", style:'margin-left:1em;border-top:0px;border-right:0px;border-left:0px;font-style'  %>
    <%= f.text_field :task_name,style:'margin-left:1em;border:2px solid black' %><br>
    <%= f.submit "Update", class:'btn btn-primary',style:'margin-left:15%' %>
<%end%>

app/views/pages/index.html.erb
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<div style="background-color: lightyellow; height: 160px; border: 2px solid black">
<h1 style="text-align: center; padding-top: 50px; font-style: italic;">My todo list</h1>
</div>

<div style="padding-right:10px; margin-top:20px;">

<%= form_for @post, url: {action: 'create'} do |f| %>
  	<%= f.label :task_name, "Write the name of the task you want to create:", style:'margin-left:1em;border-top:0px;border-right:0px;border-left:0px;font-style'  %>
    <%= f.text_field :task_name,style:'margin-left:1em;border:2px solid black' %><br>
    <%= f.submit "Create", class:'btn btn-primary',style:'margin-left:30%' %>
<%end%>

</div>


<!-- <div style="margin-left: auto; margin-right: auto"> -->
<div>
<table style="border: 2px solid black; padding:2px;text-align: center;margin-left: auto; margin-right: auto; margin-top: 10px">
    	<tr>
    		<td><b>Serial#</b></td>
    		<td><b>Name of the Task</b></td>
    		<td><b>Status</b></td>
    		<td><b>Completed</b></td>
    		<td><b>Delete</b></td>
    		<!-- <td</b></td> -->
    	</tr>

		<% @posts.each do |a| %>
    	<tr>
    	<td><%=a.id%></td>
    	<td><%= a.task_name%> 
		<a href="<%= edit_page_path(id: a.id)%>"<button style="font-size:14px"><i class="fa fa-edit"></i></button>

</a></td>
    	<td><%=a.complete%></td>
    	
    	<!-- <td><button>Completed</button></td> -->
    	  <td><%= link_to 'Update', changer_page_path(id: a.id, flags: "true"), method: 'post' %></td>
    	 	<td>
    	 		<%= link_to "Delete", page_path(id: a.id), :method => :delete %>
    	 	</td>

    	</tr>
<%end%>    
    </table>
</div>
    <p>Note: After completion of task just press the button</p>